---
chdir: /srv/tachyon/engine
environment: production
address: 0.0.0.0
port: 3000
timeout: 55
log: log/thin.log
pid: tmp/pids/thin.pid
max_conns: 1024
max_persistent_conns: 512
require: []
daemonize: true
threaded: true
no-epoll: true
servers: 1



